### ISSUE TITLE
Chores: Refactor the DB code and add Unit Tests

### ISSUE THREAD

**Issue by Haxerus** [beatlepie/4G06CapstoneProjectTeam2#237]
## Chores
- **Date**: 2024/02/16
- **Estimated Time to Complete**: 3-5 days
-  **Assignee**: @Haxerus 
- **Description/Requirements**: We need to work on the following:
1. Refactor the code that handles database interactions to be more self-contained.
2. Create Unit Tests for the simple data structure classes
3. Create Unit Tests for the refactored database code, test CRUD functions

- **Solution**:
Update and unify the database interaction code into a single class with a singleton structure. This will ensure that the database code is self-contained rather than be fragmented across multiple classes.

UPDATE (3/1/2024): Firebase functions cannot be tested through UTF so they need to be mocked up.
Functionality To be Mocked Up:
- Set/Get Async
- Authentication (Login with Email+PW)

Classes that are affected:
- Lecture
- Login
- Events

- **Notes**: NA

**Comment by beatlepie** [comment]
Attempted to make automated testing work for entire unity project, but the automated process could not import all the dependencies. Was unable to add the package due to size on GitHub, large file storage did not work either. 

Current solution: test the code individually as c# code instead of unity test
