### ISSUE TITLE
Team 11 Review: Environment Database not specified

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#270]
@samm82
Name: Team 11 Review
About: Environment Database not Specified 

Summary: There is no mention in the report about the environment in which the tests were run, such as if a separate testing database was used or if the main database was used. This should be specified in the report.

Deadline: Apr 1, 2024

Estimated Work Hours: 20 mins

**Comment by qw33ha** [comment]
As you expected, there is no testing database and everything is from the main database -- which makes perfect sense since there is still no actual data from it yet. I don't understand the meaning of having a separate database or any need to explain that because even at the end of Revision 1, we do not expect any actual user of the design. Once actual users comes in, the team will clear the testing data from the database.
From another perspective, the tests are treated as system testing, what's the purpose of having a separate database and using the setting that's different from what the user is using?
